// Shared test reporter: every suite records PASS/FAIL per test and merges
// into .deep-era/test-report.json (+ TEST-REPORT.md) in the PROJECT root.
// An AI confirming "did tests pass?" reads ONE file instead of scrolling logs.
// Suites run sequentially (npm test chains with &&), so merge-read-write is safe.
const fs = require("fs");
const path = require("path");

function reportPaths(rootDir) {
  const dir = path.join(rootDir, ".deep-era");
  return { json: path.join(dir, "test-report.json"), md: path.join(rootDir, "TEST-REPORT.md") };
}

function readReport(rootDir) {
  try {
    return JSON.parse(fs.readFileSync(reportPaths(rootDir).json, "utf8"));
  } catch {
    return { version: 1, suites: {} };
  }
}

function makeReporter(suite, rootDir) {
  const root = rootDir || process.cwd();
  const state = { pass: 0, fail: 0, tests: [] };
  const pending = [];
  function record(name, ok, detail) {
    state.tests.push({ name, ok: !!ok, at: new Date().toISOString(), detail: (detail || "").slice(0, 300) });
    if (ok) { state.pass++; console.log(`PASS ${name}`); }
    else { state.fail++; console.error(`FAIL ${name}: ${detail || ""}`); process.exitCode = 1; }
  }
  function ok(name, fn) {
    const t0 = Date.now();
    try {
      const r = fn();
      if (r && typeof r.then === "function") {
        pending.push(r.then(
          () => record(name, true, `${Date.now() - t0}ms`),
          (e) => record(name, false, `${Date.now() - t0}ms ${e && e.message ? e.message : e}`)
        ));
      } else record(name, true, `${Date.now() - t0}ms`);
    } catch (e) {
      record(name, false, `${Date.now() - t0}ms ${e && e.message ? e.message : e}`);
    }
  }
  async function finish() {
    await Promise.all(pending);
    const full = readReport(root);
    full.at = new Date().toISOString();
    try { full.deepEra = require(path.join(root, "package.json")).version; } catch { full.deepEra = "?"; }
    full.suites[suite] = { pass: state.pass, fail: state.fail, tests: state.tests };
    const totals = Object.values(full.suites).reduce((a, s) => ({ pass: a.pass + s.pass, fail: a.fail + s.fail }), { pass: 0, fail: 0 });
    full.total = totals;
    full.result = totals.fail ? "FAIL" : "PASS";
    const { json, md } = reportPaths(root);
    try { fs.mkdirSync(path.dirname(json), { recursive: true }); } catch {}
    fs.writeFileSync(json, JSON.stringify(full, null, 2));
    const lines = [`# TEST-REPORT.md (generated by deep-era test reporter)`, ``, `Result: **${full.result}** — ${totals.pass} pass, ${totals.fail} fail (${full.at})`, ``];
    for (const [sn, s] of Object.entries(full.suites)) {
      lines.push(`## ${sn}: ${s.pass} pass, ${s.fail} fail`);
      for (const t of s.tests) lines.push(`- [${t.ok ? "x" : " "}] ${t.name}${t.ok ? "" : " — " + t.detail}`);
      lines.push(``);
    }
    fs.writeFileSync(md, lines.join("\n"));
    console.log(`\n${state.pass} ${suite} tests passed${state.fail ? `, ${state.fail} FAILED` : ""} (report: .deep-era/test-report.json)`);
    return full;
  }
  return { ok, finish, pending };
}

module.exports = makeReporter;
module.exports.makeReporter = makeReporter;
module.exports.readReport = readReport;
