const fs = require("fs");
const path = require("path");

// Architecture graph from the REAL import map — no guessing.
// Writes ARCHITECTURE.md with a Mermaid flowchart (renders on GitHub natively).
function safeId(file) {
  return "n" + Buffer.from(file).toString("hex").slice(0, 12);
}

function runGraph(cwd, opts) {
  opts = opts || {};
  const { buildMap } = require("./map");
  const map = buildMap(cwd);
  const byFile = new Map(map.files.map((f) => [f.file, f]));
  let pool = map.files.filter((f) => f.role.startsWith("code"));
  let title = `Showing top 15 connected modules`;
  if (opts.for) {
    // Ego-graph: one module + its direct imports + importers.
    const key = [...byFile.keys()].find((k) => k === opts.for || k.endsWith("/" + opts.for) || k.endsWith(opts.for)) || opts.for;
    const center = byFile.get(key);
    if (!center) {
      console.log(`[deep-era] graph: no such module: ${opts.for}`);
      process.exitCode = 1;
      return { modules: 0, edges: 0 };
    }
    const keep0 = new Set([key, ...(center.imports || []), ...(center.importedBy || [])]);
    pool = pool.filter((f) => keep0.has(f.file));
    title = `Ego-graph of ${key} (+direct imports/importers)`;
  }
  // Top hubs by connection count
  let ranked = pool
    .map((f) => ({ f, links: (f.imports || []).length + (f.importedBy || []).length }))
    .sort((a, b) => b.links - a.links);
  if (!opts.full && !opts.for) {
    ranked = ranked.slice(0, 15);
    title = `Showing top 15 connected modules`;
  } else if (opts.full) {
    ranked = ranked.slice(0, 80);
    title = `Full graph (${ranked.length} modules, capped at 80 for readability)`;
  }
  const keep = new Set(ranked.map((r) => r.f.file));
  const edges = [];
  for (const { f } of ranked) {
    for (const d of (f.imports || [])) {
      const key = byFile.has(d) ? d : d.replace(/^\.\//, "");
      if (keep.has(key)) edges.push(`  ${safeId(f.file)}-->${safeId(key)}`);
    }
  }
  const nodes = [...keep].map((fl) => {
    const f = byFile.get(fl);
    const label = `${fl} [${f.role.replace("code-", "")}]`;
    return `  ${safeId(fl)}["${label}"]`;
  });
  const md = `# Architecture (generated by deep-era from real imports)\n\nGenerated: ${new Date().toISOString()} | Files: ${map.counts.total} | ${title}\n\n\`\`\`mermaid\nflowchart TD\n${nodes.join("\n")}\n${edges.slice(0, 120).join("\n") || "  n0[\"no internal imports found\"]"}\n\`\`\`\n\nMost-imported (change carefully):\n` + map.files.filter((f) => (f.importedBy || []).length).sort((a, b) => b.importedBy.length - a.importedBy.length).slice(0, 5).map((f) => `- ${f.file} (used by ${f.importedBy.length})`).join("\n") + "\n";
  fs.writeFileSync(path.join(cwd, "ARCHITECTURE.md"), md);
  console.log(`[deep-era] ARCHITECTURE.md: ${keep.size} modules, ${edges.length} edges (renders on GitHub)`);
  return { modules: keep.size, edges: edges.length };
}

module.exports = { runGraph };
