// guidance.js — routes a task to the right files and the right order.
//
// WHY: deep-era could verify but not navigate. get_context ranked files by filename
// substring, so an agent asking "add rate limiting to the API" got whichever file
// happened to contain the word "api" — often a test, a fixture, or a config. Then the
// agent guessed, wrote in the wrong place, and shipped slop. That is the exact failure
// the v0.47 work was meant to stop, one step earlier.
//
// THIS ENGINE answers, before any code is written:
//   1. What kind of task is this?        (classified from the words used)
//   2. Which files must be read first?    (the convention layer of this repo)
//   3. Which files must NOT be touched?   (generated, vendored, lock, fixtures)
//   4. What order do the steps run in?    (the loop that prevents rework)
//   5. What does this repo already decide? (locked decisions the agent would otherwise
//                                           contradict by accident)
//
// Everything is derived from the real project: its file map, its import graph, its
// memory, and its own conventions. No hardcoded framework assumptions.
const fs = require("fs");
const path = require("path");

// --- task taxonomy -----------------------------------------------------------
// Each kind has: matching cues, the file roles it touches, and the safe order.
const TASK_KINDS = [
  {
    kind: "bugfix",
    cues: ["fix", "bug", "broken", "crash", "error", "fails", "failing", "regression", "wrong", "not working", "issue", "stack", "trace", "exception", "undefined", "null"],
    read: ["test", "code"],
    order: ["reproduce", "locate", "fix", "prove"],
    warn: "Read the failing test FIRST and make it fail before changing anything. A fix with no failing test is not a fix.",
  },
  {
    kind: "feature",
    cues: ["add", "implement", "create", "build", "new", "support", "feature", "endpoint", "button", "page", "route", "field"],
    read: ["convention", "code", "test"],
    order: ["match-conventions", "scaffold", "implement", "test"],
    warn: "Find the closest existing example and copy its shape. A new file that does not match the local convention is the start of slop.",
  },
  {
    kind: "refactor",
    cues: ["refactor", "clean", "rename", "extract", "simplify", "restructure", "organize", "migrate", "move", "dedupe", "duplicate"],
    read: ["code", "test"],
    order: ["prove-green", "map-dependents", "change", "prove-green-again"],
    warn: "Snapshot first. This is the one task where breaking something is likely, so make it reversible before you start.",
  },
  {
    kind: "security",
    cues: ["auth", "authenticate", "login", "password", "secret", "token", "permission", "injection", "xss", "csrf", "sanitize", "encrypt", "vulnerability", "exploit"],
    read: ["code", "config", "test"],
    order: ["map-attack-surface", "fix", "add-negative-test", "verify"],
    warn: "Write the failing exploit test FIRST. If you cannot reproduce the attack, you have not fixed it.",
  },
  {
    kind: "performance",
    cues: ["slow", "optimize", "performance", "perf", "latency", "speed", "memory", "leak", "cpu", "bottleneck", "cache", "n+1"],
    read: ["code", "test"],
    order: ["measure", "find-the-cause", "change-one-thing", "measure-again"],
    warn: "Measure before and after, and paste both numbers. An optimization with no before-number is a guess.",
  },
  {
    kind: "test",
    cues: ["test", "coverage", "assert", "spec", "mock", "fixture", "unit test", "integration"],
    read: ["code", "test"],
    order: ["read-target", "write-failing-test", "make-pass"],
    warn: "A test that cannot fail is worse than no test: it reports safety that does not exist. Assert on real values.",
  },
  {
    kind: "docs",
    cues: ["document", "readme", "docs", "comment", "jsdoc", "explain", "guide", "changelog"],
    read: ["code", "doc"],
    order: ["read-the-code", "write", "verify-links"],
    warn: "Only document behaviour you read in the code. Documentation invented from assumption is a new bug source.",
  },
];

// Files an agent must never edit without an explicit instruction.
function forbiddenFiles() {
  return [
    { pattern: /(^|\/)(node_modules|vendor|\.venv|venv)\//, why: "third-party code, not yours" },
    { pattern: /(^|\/)(dist|build|out|\.next|target)\//, why: "build output, regenerated from source" },
    { pattern: /package-lock\.json$|yarn\.lock$|pnpm-lock\.yaml$|Cargo\.lock$|poetry\.lock$/, why: "lockfile, regenerated by the package manager" },
    { pattern: /(^|\/)tests?\/fixtures?\//, why: "fixture, holds deliberately broken input for the scanners" },
    { pattern: /\.min\.(js|css)$/, why: "minified artifact" },
    { pattern: /(^|\/)\.deep-era\//, why: "deep-era's own state directory" },
  ];
}

// The convention layer: files that describe how THIS repo wants code written.
function conventionFiles(cwd, map) {
  const names = new Set(map.files.map((f) => f.file));
  const wanted = [
    "AGENTS.md", "CLAUDE.md", "CONTRIBUTING.md", "ARCHITECTURE.md",
    ".cursorrules", ".windsurfrules", "README.md", "docs/CONVENTIONS.md",
    "DEVELOPMENT.md", ".editorconfig", "tsconfig.json", "eslint.config.js",
  ];
  const found = wanted.filter((n) => names.has(n));
  // Per-language style configs actually present.
  for (const f of map.files) {
    if (/^(eslint\.|\.eslintrc|prettier\.|\.prettierrc|\.editorconfig|ruff\.toml|pyproject\.toml|\.flake8|rubocop\.yml|\.rubocop)/.test(f.file)) {
      if (!found.includes(f.file)) found.push(f.file);
    }
  }
  return found;
}

function classify(taskText) {
  const t = (taskText || "").toLowerCase();
  if (!t.trim()) return { kind: "unknown", score: 0, all: [] };
  const scored = TASK_KINDS.map((k) => {
    let s = 0;
    for (const cue of k.cues) if (t.includes(cue)) s += cue.includes(" ") ? 3 : 2;
    return { kind: k.kind, score: s, def: k };
  }).sort((a, b) => b.score - a.score);
  return { kind: scored[0].kind, score: scored[0].score, all: scored };
}

// Task verbs describe the ACTION, not the SUBJECT. "fix the crash" must route by
// "crash", never by "fix" — otherwise every task in a repo containing src/fix.js
// gets routed to src/fix.js, which is worse than no routing at all.
const GENERIC_VERBS = new Set([
  "fix", "add", "make", "use", "get", "set", "run", "new", "the", "and", "for",
  "with", "that", "this", "please", "need", "want", "help", "code", "file",
  "files", "change", "update", "also", "then", "into", "from", "have", "some",
  "should", "would", "could", "about", "there", "here", "them", "does",
]);

// Where should the agent actually start reading? Import-graph aware.
function routeFiles(cwd, map, taskText, limit = 6) {
  const t = (taskText || "").toLowerCase();
  // Drop the project's own identity words. "fix deep-era" must route by "fix", not
  // by the fact that half the repo is named deep-era.
  const projectWords = new Set(
    String((map && map.project) || (cwd ? path.basename(cwd).toLowerCase() : ""))
      .split(/[^a-z0-9]+/).filter((w) => w.length > 2)
  );
  const words = t.split(/[^a-z0-9_]+/).filter((w) => w.length > 2 && !projectWords.has(w) && !GENERIC_VERBS.has(w));
  const byFile = new Map(map.files.map((f) => [f.file, f]));

  const scored = map.files.map((f) => {
    const name = f.file.toLowerCase();
    const base = name.split("/").pop();
    let score = 0;
    const reasons = [];

    // Direct name hit is the strongest signal.
    for (const w of words) {
      if (base.includes(w)) { score += 5; reasons.push(`name~"${w}"`); }
    }
    // Path segment hit.
    for (const w of words) {
      if (name.includes(w) && !base.includes(w)) { score += 2; reasons.push(`path~"${w}"`); }
    }
    // Hubs are where real logic lives, but a generic hub matches every task and
    // turns the routing table into noise. Only count it when the file ALSO matched
    // on something the task actually said.
    const named = reasons.length > 0;
    if (named && (f.importedBy || []).length) {
      score += Math.min((f.importedBy.length) * 0.25, 1.5);
    }
    // Penalise noise: fixtures, tests, configs are rarely the thing to edit. A
    // fixture is excluded outright, never merely ranked low — listing one in a
    // "you will edit this" list contradicts the DO-NOT-EDIT rule printed below it.
    if (/fixtures?\//.test(name)) return { f, score: -100, reasons: ["fixture-avoid"] };
    if (/tests?\//.test(name)) score -= 1.5;
    if (/\.(json|yml|yaml|toml|lock)$/.test(name)) score -= 1;
    if (/\.md$/.test(name)) score -= 0.5;

    return { f, score, reasons };
  });

  // A routing answer must be sharp. When nothing matched on the words the task used,
  // saying so beats listing six plausible-looking files: an agent that is told
  // "search by content" will search, and one that is handed a list will guess.
  const top = scored.filter((s) => s.score > 0).sort((a, b) => b.score - a.score).slice(0, limit);
  const strong = top.filter((s) => s.reasons.some((r) => r.startsWith("name~") || r.startsWith("path~")));
  if (!strong.length) return { primary: [], dependents: [], noMatch: true };

  // Pull in one hop of dependents: changing a hub means its callers must be checked.
  const dependents = [];
  for (const s of top) {
    for (const dep of s.f.importedBy || []) {
      if (!top.find((x) => x.f.file === dep) && !dependents.find((d) => d.file === dep) && dependents.length < 4) {
        const df = byFile.get(dep);
        if (df) dependents.push({ file: dep, role: df.role, why: `imports ${s.f.file} — check it still works` });
      }
    }
  }
  return { primary: top.map((s) => ({ file: s.f.file, role: s.f.role, score: +s.score.toFixed(2), why: s.reasons.join(", ") })), dependents };
}

// Locked decisions in this project's memory: the agent would otherwise contradict them.
function lockedDecisions(cwd) {
  try {
    const { readAll } = require("./memory");
    return readAll(cwd, 500).filter((e) => e.kind === "decision").slice(-8).map((e) => e.text);
  } catch { return []; }
}

// Prior failures worth not repeating.
function priorErrors(cwd) {
  try {
    const { readAll } = require("./memory");
    return readAll(cwd, 500).filter((e) => e.kind === "error").slice(-5).map((e) => e.text);
  } catch { return []; }
}

// The honest health of the repo RIGHT NOW: what will block you at the end.
function blockers(cwd, map) {
  const out = [];
  const names = new Set(map.files.map((f) => f.file));

  if (!names.has("package.json") && !names.has("requirements.txt") && !names.has("go.mod") &&
      !names.has("Cargo.toml") && !names.has("pyproject.toml") && !names.has("pom.xml") &&
      !names.has("composer.json") && !names.has("Gemfile") && !names.has("pubspec.yaml")) {
    out.push("No dependency manifest found — nothing declares how to run or test this project.");
  }
  const hasSrc = map.files.some((f) => /^(src|lib|app|backend)\//.test(f.file));
  const hasTest = map.files.some((f) => /(^|\/)(tests?|__tests__|spec)\//.test(f.file) || /\.test\.[jt]sx?$/.test(f.file));
  if (hasSrc && !hasTest) out.push("Source exists but there is no test folder — nothing will prove your change works.");
  if (!names.has(".gitignore")) out.push("No .gitignore — secrets and build output can be committed by accident.");
  if (map.counts && map.counts.truncated) out.push(`File map hit the 2000-file cap (truncated) — some files were not considered. Add .deep-eraignore for generated dirs.`);

  // Live check of what will actually fail the final gate.
  try {
    const { semanticScan } = require("./semantics");
    const sem = semanticScan(cwd, map.files).filter((x) => x.sev === "high");
    if (sem.length) out.push(`${sem.length} existing high-severity semantic bug(s) will be attributed to your work. Fix or note them first.`);
  } catch {}
  return out;
}

// --- the briefing the agent actually reads -----------------------------------
function buildBrief(cwd, map, taskText) {
  const cls = classify(taskText);
  const def = cls.def || null;
  const conv = conventionFiles(cwd, map);
  const routed = routeFiles(cwd, map, taskText, 6);
  const decisions = lockedDecisions(cwd);
  const errors = priorErrors(cwd);
  const block = blockers(cwd, map);

  const lines = [];
  lines.push(`TASK CLASS: ${cls.kind}${cls.score === 0 ? " (no clear signal — ask the user before editing)" : ""}`);
  if (def) lines.push(`WHY IT MATTERS: ${def.warn}`);
  lines.push("");

  if (conv.length) {
    lines.push("READ FIRST — this repo's own rules (obey them over your defaults):");
    for (const c of conv) lines.push(`  - ${c}`);
  } else {
    lines.push("READ FIRST — no convention file found. That is itself a risk: match the closest existing file's style by hand.");
  }
  lines.push("");

  if (routed.noMatch) {
    lines.push("LIKELY TOUCH — nothing matched the words in your task. Do NOT guess a location.");
    lines.push("  Use `deep-era search <term>` (searches CONTENT, not just filenames) before editing.");
  } else {
    lines.push("LIKELY TOUCH — read these before writing anything:");
    for (const p of routed.primary) lines.push(`  - ${p.file}  (${p.role})  [${p.why}]`);
  }
  if (routed.dependents.length) {
    lines.push("ALSO AFFECTED — these import what you are about to change:");
    for (const d of routed.dependents) lines.push(`  - ${d.file}  (${d.why})`);
  }
  lines.push("");

  lines.push("DO NOT EDIT without an explicit instruction:");
  for (const f of forbiddenFiles()) lines.push(`  - ${f.pattern.source}  — ${f.why}`);
  lines.push("");

  if (decisions.length) {
    lines.push("LOCKED DECISIONS in this project — violating these is a failure:");
    for (const d of decisions) lines.push(`  - ${d}`);
  } else {
    lines.push("LOCKED DECISIONS: none recorded yet. If you make one, remember it so the next session cannot contradict you.");
  }
  lines.push("");

  if (errors.length) {
    lines.push("FAILED BEFORE in this project — do not repeat:");
    for (const e of errors) lines.push(`  - ${e}`);
    lines.push("");
  }

  if (block.length) {
    lines.push("BLOCKERS THAT WILL COST YOU AT THE END:");
    for (const b of block) lines.push(`  ! ${b}`);
    lines.push("");
  }

  lines.push("ORDER OF WORK (do not reorder):");
  const order = def ? def.order : ["understand", "locate", "change", "prove"];
  order.forEach((s, i) => lines.push(`  ${i + 1}. ${s}`));
  lines.push("");
  lines.push("BEFORE you claim done: `deep-era check` must be PASS. Paste its real output — never describe it from memory.");

  return {
    taskClass: cls.kind,
    confidence: cls.score === 0 ? "none" : cls.score >= 4 ? "high" : "medium",
    conventions: conv,
    likelyTouch: routed.primary,
    alsoAffected: routed.dependents,
    lockedDecisions: decisions,
    priorErrors: errors,
    blockers: block,
    order,
    forbidden: forbiddenFiles().map((f) => ({ pattern: f.pattern.source, why: f.why })),
    brief: lines.join("\n"),
  };
}

module.exports = { buildBrief, classify, routeFiles, conventionFiles, forbiddenFiles, TASK_KINDS };
