const fs = require("fs");
const path = require("path");

// Session receipt: ONE file proving what the AI did — goal, steps, changes,
// verdict. The human opens .deep-era/LAST-SESSION.md instead of guessing.
// Written from existing logs + git state; collects nothing new.
function runReceipt(cwd) {
  const lines = [];
  lines.push(`# LAST SESSION (generated by deep-era)`);
  lines.push(``);
  lines.push(`Generated: ${new Date().toISOString()}`);
  try {
    const log = fs.readFileSync(path.join(cwd, ".deep-era", "logs", "steps.log"), "utf8").split("\n").filter(Boolean);
    lines.push(``);
    lines.push(`## Steps (${log.length} total, last 15 shown)`);
    for (const l of log.slice(-15)) lines.push(`- ${l}`);
  } catch {
    lines.push(`## Steps\n- (no steps logged yet — AI worked outside deep-era?)`);
  }
  try {
    const last = JSON.parse(fs.readFileSync(path.join(cwd, ".deep-era", "last-doctor.json"), "utf8"));
    lines.push(``);
    lines.push(`## Last verdict: ${last.failed ? "FAIL" : "PASS"} (fails=${last.failed}, security=${last.security}, guard=${last.guard}, deps=${last.deps}, at=${last.at})`);
  } catch {
    lines.push(`## Last verdict: UNKNOWN (doctor never ran here)`);
  }
  try {
    const { execSync } = require("child_process");
    const st = execSync("git status --short", { cwd, timeout: 8000 }).toString().trim();
    lines.push(``);
    lines.push(`## Working tree`);
    lines.push(st ? "```\n" + st.slice(0, 2000) + "\n```" : "- clean");
  } catch {
    lines.push(`## Working tree\n- (not a git repo)`);
  }
  const md = lines.join("\n") + "\n";
  fs.mkdirSync(path.join(cwd, ".deep-era"), { recursive: true });
  fs.writeFileSync(path.join(cwd, ".deep-era", "LAST-SESSION.md"), md);
  console.log(`[deep-era] receipt: .deep-era/LAST-SESSION.md (open this ONE file to see everything)`);
  return md;
}

// Status screen: whole platform state in one terminal screen.
function runStatus(cwd) {
  const { buildMap } = require("./map");
  const { spendReport } = require("./spend");
  const { listSnapshots } = require("./snapshot");
  const { readAll } = require("./memory");
  let map;
  try {
    map = JSON.parse(fs.readFileSync(path.join(cwd, ".deep-era", "map.json"), "utf8"));
  } catch {
    map = buildMap(cwd);
  }
  let verdict = "UNKNOWN";
  try {
    const last = JSON.parse(fs.readFileSync(path.join(cwd, ".deep-era", "last-doctor.json"), "utf8"));
    verdict = last.failed ? `FAIL (${last.failed})` : "PASS";
  } catch {}
  const sp = spendReport(cwd);
  console.log(`[deep-era] status: ${cwd}`);
  console.log(`  project: ${map.stack.kind}, ${map.counts.total} files${map.counts.truncated ? " (TRUNCATED)" : ""}`);
  console.log(`  last audit: ${verdict} | memory: ${readAll(cwd).length} entries | snapshots: ${listSnapshots(cwd).length}`);
  console.log(`  AI spend: ${sp.tokens.toLocaleString()} tokens (~${Object.values(sp.estimate)[1]} standard)`);
  console.log(`  proof files: .deep-era/LAST-SESSION.md, ERROR-REPORT.md, TEST-REPORT.md`);
  return { verdict, files: map.counts.total };
}

module.exports = { runReceipt, runStatus };
